name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths-ignore:
      - "docs/**"

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: ministryofjustice/tech-docs-github-pages-publisher:v4.0.0
    steps:
    - uses: actions/checkout@v4
    - name: Publish
      run: /scripts/deploy.sh
